### ISSUE TITLE
REST API-Device ID 등록(POST)

### ISSUE THREAD

**Issue by ReportSubmit** [GamePlatform/Campaign-Server#14]
1. request parameter ( JSON)

2. response

3. url 정하기

4. 위키에 적기

5. 구현

**Comment by hyeongyun0916** [comment]
1. device_id(VARCHAR(50)), app_id(VARCHAR(50)) //둘다 non Null
2. 
쿼리에서 에러가 날 경우 result: -1, msg: err(쿼리를 날려서 나온 에러)
파라미터 둘 중 하나가 비어있을 경우 result: -2, msg: check device_id and app_id
같은 device_id 와 app_id로 날아올 경우 result: -3, msg: alerdy exist
성공했을 경우 result: 0

3. /registerDevice
