### ISSUE TITLE
Server DB 접속

### ISSUE THREAD

**Issue by hyeongyun0916** [GamePlatform/Campaign-Server#26]
서버에 있는 디비에 접속하려고 할때
{
    "code": "ECONNREFUSED",
    "errno": "ECONNREFUSED",
    "syscall": "connect",
    "address": "211.253.28.194",
    "port": 3306,
    "fatal": true
}
위와 같은 오류가 나면서 접속이 안됩니다.

**Comment by donnaknew** [comment]
전에는 접속이 되셧나요??

**Comment by hyeongyun0916** [comment]
아뇨 접속이 안되어서 지난 일요일에 원준님께 여쭤봤는데 이건 일단 이슈로 남기자고 하시더라구요 그래서 남겼습니다!

**Comment by donnaknew** [comment]
아 넵 ㅋㅋ

**Comment by ReportSubmit** [comment]
mysql은 로컬을 위한 db라서 외부 db와 연결시에는 따로 소켓을 열어 연결해야한다고 합니다.

https://stackoverflow.com/questions/4523459/mysql-can-connect-remotely-but-not-locally
